baseURL = "https://blueyfest.dog"
languageCode = "en-us"
title = "BlueyFest"

# Google Analytics data
googleAnalytics = "G-6SKB2FWYS5"

[params]
  scheduleApiUriDev = "https://schedule-api.blueyfest.dog/schedule"
  scheduleApiUri = "https://schedule-api.blueyfest.dog/schedule"
  countdownDate = "2023-04-01T15:00:00-04:00"
  messDate = "2023-04-01T18:00:00-04:00"

# this lets use use HTML in our pages if we are so inclined.
[markup.goldmark.renderer]
unsafe = true

